[package]
name = "levin"
version = "0.1.0"
authors = ["LINEZH <huizhaoline@gmail.com>"]
edition = "2018"
description = "monero levein protocol, some code was coppied from xmr"

[dependencies]
tokio = "0.1.13"
chrono = "0.4"
hex = "0.3.2"
rand = "0.6"
bytes = "0.4.12"
log = "0.4.6"